### ISSUE TITLE
convert selection to image

### ISSUE THREAD

**Issue by HoracioEspinosa** [foo123/HAAR.js#23]
hi, how i can convert my selection area to an image and how i can train my own haarcascade, i ever get an error, my error is "rects is undefined" thanks

**Comment by foo123** [comment]
Sorry for late reply. Which selection area do you mean, the recognised feature that you get AFTER running HAAR.js on an image or a selection area that is stored in the internal canvas? 

For the first case you have the coordinates of the area and you can use canvas methods to crop the initial image into a selection image.

For the second case there is a canvas object that stores the image in HAAR.js you can access this canvas and display it in javascript. 

I have replied to your [other issue](https://github.com/foo123/HAAR.js/issues/24) as well. Let me know if you need further information.
