### ISSUE TITLE
Cannot read property 'rects' of undefined

### ISSUE THREAD

**Issue by HoracioEspinosa** [foo123/HAAR.js#24]
this is my haar file

`<?xml version="1.0"?>
<opencv_storage>
<myhaar type_id="opencv-haar-classifier">
  <size>
    20 20</size>
  <stages>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  7 16 6 4 -1.</_>
                <_>
                  7 18 6 2 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>-0.0323070399463177</threshold>
            <left_val>0.8604652881622315</left_val>
            <right_val>-1.0000020265579224</right_val></_></_></trees>
      <stage_threshold>0.8604652881622315</stage_threshold>
      <parent>-1</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  0 2 4 11 -1.</_>
                <_>
                  2 2 2 11 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>0.0154317598789930</threshold>
            <left_val>-1.</left_val>
            <right_val>0.6949151754379273</right_val></_></_></trees>
      <stage_threshold>0.6949151754379273</stage_threshold>
      <parent>0</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  1 0 15 16 -1.</_>
                <_>
                  1 4 15 8 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>0.1195845976471901</threshold>
            <left_val>-0.8895025849342346</left_val>
            <right_val>0.7351595759391785</right_val></_></_>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  0 6 20 7 -1.</_>
                <_>
                  5 6 10 7 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>0.1091756969690323</threshold>
            <left_val>-0.8640195131301880</left_val>
            <right_val>0.6678310036659241</right_val></_></_></trees>
      <stage_threshold>-0.2216715961694717</stage_threshold>
      <parent>1</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  0 4 20 2 -1.</_>
                <_>
                  5 4 10 2 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>0.0437872111797333</threshold>
            <left_val>-0.6330271959304810</left_val>
            <right_val>0.7582414746284485</right_val></_></_>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  11 17 2 3 -1.</_>
                <_>
                  11 18 2 1 3.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>3.7808620836585760e-003</threshold>
            <left_val>-0.7312806248664856</left_val>
            <right_val>0.7276245951652527</right_val></_></_></trees>
      <stage_threshold>0.0269609093666077</stage_threshold>
      <parent>2</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  6 0 8 2 -1.</_>
                <_>
                  6 1 8 1 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>0.0229575894773006</threshold>
            <left_val>-0.5850620269775391</left_val>
            <right_val>0.8867923021316528</right_val></_></_>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  15 6 4 14 -1.</_>
                <_>
                  15 13 4 7 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>-0.0248031206429005</threshold>
            <left_val>0.3715035021305084</left_val>
            <right_val>-0.7250819802284241</right_val></_></_></trees>
      <stage_threshold>-0.2135584950447083</stage_threshold>
      <parent>3</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  8 0 3 2 -1.</_>
                <_>
                  8 0 3 1 2.</_></rects>
              <tilted>1</tilted></feature>
            <threshold>-3.0379199888557196e-003</threshold>
            <left_val>0.5267180204391480</left_val>
            <right_val>-1.0000020265579224</right_val></_></_></trees>
      <stage_threshold>0.5267180204391480</stage_threshold>
      <parent>4</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  5 15 3 4 -1.</_>
                <_>
                  5 16 3 2 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>1.7002030508592725e-003</threshold>
            <left_val>0.5254240036010742</left_val>
            <right_val>-0.7560986876487732</right_val></_></_>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  0 10 20 4 -1.</_>
                <_>
                  5 10 10 4 2.</_></rects>
              <tilted>0</tilted></feature>
            <threshold>0.1169022992253304</threshold>
            <left_val>-0.6004660129547119</left_val>
            <right_val>0.6980428099632263</right_val></_></_></trees>
      <stage_threshold>-0.0750420093536377</stage_threshold>
      <parent>5</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  2 7 11 2 -1.</_>
                <_>
                  2 7 11 1 2.</_></rects>
              <tilted>1</tilted></feature>
            <threshold>0.0232701301574707</threshold>
            <left_val>-1.</left_val>
            <right_val>0.3333333134651184</right_val></_></_></trees>
      <stage_threshold>0.3333333134651184</stage_threshold>
      <parent>6</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  7 6 9 3 -1.</_>
                <_>
                  6 7 9 1 3.</_></rects>
              <tilted>1</tilted></feature>
            <threshold>2.3264440242201090e-003</threshold>
            <left_val>0.3698633015155792</left_val>
            <right_val>-1.0000009536743164</right_val></_></_></trees>
      <stage_threshold>0.3698633015155792</stage_threshold>
      <parent>7</parent>
      <next>-1</next></_>
    <_>
      <trees>
        <_>
          <_>
            <feature>
              <rects>
                <_>
                  7 6 8 3 -1.</_>
                <_>
                  6 7 8 1 3.</_></rects>
              <tilted>1</tilted></feature>
            <threshold>-3.1593269668519497e-003</threshold>
            <left_val>-1.</left_val>
            <right_val>0.4285714924335480</right_val></_></_></trees>
      <stage_threshold>0.4285714924335480</stage_threshold>
      <parent>8</parent>
      <next>-1</next></_></stages></myhaar>
</opencv_storage>
`

Ever say this error, i convert it with your batch files but anything, thanks.

**Comment by foo123** [comment]
Sorry for late reply, can you post here the javascript (or json) file that you get from converting the above xml to javascript using the harrtojs tool in the cascades folder?
