### ISSUE TITLE
Can I use this for real time face tracking?

### ISSUE THREAD

**Issue by shubhampk37** [foo123/HAAR.js#25]
Actually, I had used Haar cascade frontal face detector in python, but I want to use it in my node project, searching for the javascript implementation  I came around this project. So I wanted to know if this can work for real time face detection in js?
The functionality that I'm working on is, when capturing the video from the webcam, if the face is non-frontal ,the face will be not detected and then alert the user to look back at the screen.
Please comment on its feasibility implementing in javascript.

**Comment by foo123** [comment]
It is possible (others have already used this in real-time).
You can use the `detectSync` method for immediate results (althopugh it might blobk)  else use 'detect' for async and slightly slower but non-blocking. Let me know how it goes
