### ISSUE TITLE
Parallel.js examples not working

### ISSUE THREAD

**Issue by bvarilone** [foo123/HAAR.js#26]
When running any of the [Live Examples](https://github.com/foo123/HAAR.js#live-examples) with _Parallel_ enabled, a runtime error, "ye is undefined", occurs. The issue happens in Chrome Version 118.0.5993.117 (Official Build) (64-bit) as well as other browsers.

- [Interactive Face Detection with Parallel Enabled](https://foo123.github.io/examples/face-detection/?parallel)
- [Many Faces Detection with Parallel Enabled](https://foo123.github.io/examples/faces-detection/?parallel)
- [Interactive Mouth Detection with Parallel Enabled](https://foo123.github.io/examples/mouth-detection/?parallel)

![2023-10-28_05-56-haarjs-paralleljs-not-working](https://github.com/foo123/HAAR.js/assets/5770377/c0946ac0-a789-452b-b77f-2354de17e127)

![2023-10-28_05-56-haarjs-paralleljs-ye-is-not-defined](https://github.com/foo123/HAAR.js/assets/5770377/71c4b3ce-5f0e-4911-bc9f-5d194d917cde)

**Comment by foo123** [comment]
`Math` renamed to `stdMath` was undefined in Worker. Fixed in v.1.0.7.

Thank you! Cheers!
